config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'contact', to: 'welcome#contact'

  get 'repos/:id', to: 'repositories#show', as: :repository
  get ':id', to: 'apps#show', as: :app
  get ':id/terms', to: 'apps#terms', as: :app_terms
  get ':id/privacy', to: 'apps#privacy', as: :app_privacy

  root 'welcome#index'

  match '*path', to: 'r404#not_found', via: :all
end

app/models/application_data.rb
# frozen_string_literal: true

class ApplicationData < ActiveData::Base
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true

  before_action :set_raven_context

  private

  def set_raven_context
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def class_hierarchy(options = [], delimiter = ' ')
    options.map(&:inspect).join(delimiter).delete('",[]')
  end
end

app/views/apps/_app.html.haml
.myg-card
  = link_to app, class: 'myg-card__top' do
    = image_tag app.logo
  .myg-card__bottom
    .wrapper
      .myg-badge__container
        - if app.released_at && app.released_at > Time.now - 1.month
          %p.myg-badge.success New! 🚀
        - if app.beta
          %p.myg-badge.error Beta 🔥
        - if app.url
          %p.myg-badge Web
        - if app.android
          %p.myg-badge Android
        - if app.ios
          %p.myg-badge iOS
        - if app.windows
          %p.myg-badge Windows
        - if app.chrome
          %p.myg-badge Chrome
      %h3= app.name
      %p= app.description
    = link_to('Learn more', app_url(name: app.name),
              class: 'myg-button--secondary')

app/views/layouts/application.html.haml
= mozaic do
  = mozaic_area :application do
    = yield

app/views/layouts/mozaic.html.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport',
           content: 'user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1' }

    = metamagic(site: 'Jonas Hübotter', title: [:title, :site],
                separator: ' - ',
                description: t('title'),
                keywords: ['developer', 'designer'])

    %link{ rel: 'apple-touch-icon', sizes: '76x76',
      href: request.base_url + '/icon_76x76.png' }
    %link{ rel: 'apple-touch-icon', sizes: '120x120',
      href: request.base_url + '/icon_120x120.png' }
    %link{ rel: 'apple-touch-icon', sizes: '152x152',
      href: request.base_url + '/icon_152x152.png' }
    %link{ rel: 'icon', sizes: '192x192',
      href: request.base_url + '/icon_192x192.png' }
    %link{ rel: 'icon', sizes: '256x256',
      href: request.base_url + '/icon_256x256.png' }
    %link{ rel: 'icon', sizes: '384x384',
      href: request.base_url + '/icon_384x384.png' }
    %link{ rel: 'icon', sizes: '512x512',
      href: request.base_url + '/icon_512x512.png' }
    %link{ rel: 'msapplication-square70x70logo',
      content: request.base_url + '/icon_70x70.png' }
    %link{ rel: 'msapplication-square150x150logo',
      content: request.base_url + '/icon_150x150.png' }
    -# %link{ rel: 'msapplication-wide310x150logo',
    -#   content: request.base_url + '/icon_310x150.png' }
    %link{ rel: 'msapplication-square310x310logo',
      content: request.base_url + '/icon_310x310.png' }

    = favicon_link_tag '/favicon.ico'

    = component 'layouts/google_analytics'
    = component('seo/schema', type: :person, name: 'Jonas Hübotter',
                email: 'me@jonhue.me', address: 'Berlin', gender: 'male',
                job_title: 'Software Developer', url: 'https://jonhue.me',
                image: 'https://jonhue.me/512x512.png',
                description: t('title'))

    = stylesheet_pack_tag('application', media: 'all',
                          'data-turbolinks-track': 'reload')
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    = csrf_meta_tags

    = area :head

  %body.myg.myg-layout{ class: class_hierarchy([params[:controller].split('/'), action_name]) }
    = mozaic_area do
      = yield

app/views/mozaic/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= options[:tracking_id] %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<%= options[:tracking_id] %>');
</script>

app/views/repositories/_repository.html.haml
.myg-card
  .myg-card__top
  .myg-card__bottom
    .wrapper
      .myg-badge__container
        - if repository.created_at > Time.now - 1.month
          %p.myg-badge.success New! 🚀
        - if repository.discontinued
          %p.myg-badge.error Discontinued
        - elsif repository.updated_at > Time.now - 1.day
          %p.myg-badge.error On... 🔥
        %p.myg-badge
          = repository.language
        - if repository.stars.positive?
          %p.myg-badge
            = repository.stars
            ⭐️
      %h3= repository.name
      %p= emojify(repository.description)
      %p.sm= link_to(updated_time_ago(repository.updated_at),
                      repository.github,
                      class: 'myg-text__hyperlink -inherit',
                      target: '_blank')
    = link_to('Learn more', repository_url(name: repository.name),
              class: 'myg-button--secondary')

app/views/welcome/index.html.haml
%section#links
  #social
    = link_to(Settings.social.linkedin, target: '_blank') do
      %i.nc.nc-logo-linkedin
    = link_to(Settings.social.github, target: '_blank') do
      %i.nc.nc-logo-github

  = link_to(t('contact'), "mailto:#{Settings.email}",
            class: 'button sec')

%section#content
  %section#hero
    %h1= t('title')

    #subscribe
      %p= t('subscribe.content')
      %p.mobile
        = t('footer',
            github: link_to('GitHub', Settings.social.github),
            medium: link_to('Medium', Settings.social.medium),
            behance: link_to('Behance', Settings.social.behance)).html_safe
      = link_to(t('subscribe.title'), 'javascript:void(0)', class: 'button')
      = link_to('javascript:void(0)', id: 'more') do
        %i.nc.nc-tail-triangle-down-2
        %p= t('more')

  %section#apps
    %h3= t('apps.title')

    .wrapper
      = link_to('https://github.com/quik-lang/quik', target: '_blank') do
        %h2= t('apps.quik.title')
        %p= t('apps.quik.content')
      = link_to('https://github.com/jonhue/plaain', target: '_blank') do
        %h2= t('apps.plaain.title')
        %p= t('apps.plaain.content')
      = link_to('https://github.com/jonhue/tip-the-world-cup', target: '_blank') do
        %h2= t('apps.tip_the_world_cup.title')
        %p= t('apps.tip_the_world_cup.content')

  %footer
    %p= t('footer',
          github: link_to('GitHub', Settings.social.github, target: '_blank'),
          medium: link_to('Medium', Settings.social.medium, target: '_blank'),
          behance: link_to('Behance', Settings.social.behance, target: '_blank')).html_safe

app/views/welcome/privacy.html.haml
- meta title: 'Privacy Policy', description: 'I value your anonymity and do not use your data unless you want me to.'
- append :head do
    = component 'seo/schema', type: :article, headline: 'Privacy Policy', in_language: 'English'


%section#policy
    .myg-wrap--tablet
        %h1 Privacy Policy

        %p This service is intended for use as is.
        %p This page is used to inform visitors regarding my policies with the collection, use, and disclosure of personal information if anyone decided to use my service.
        %p If you choose to use my service, then you agree to the collection and use of information in relation to this policy. The personal information that I collect is used for providing and improving the service. I will not use or share your information with anyone except as described in this privacy policy.

        %h3 Information Collection and Use

        %p For a better experience, while using our service, I may require you to provide us with certain personally identifiable information, including but not limited to email, first and last name.
        %p This service does use third party services that may collect information used to identify you.

        %h3 Log Data

        %p I want to inform you that whenever you use my service, in a case of an error in the app I collect data and information (through third party products) on your phone called log data. This log data may include information such as your device Internet Protocol (IP) address, device name, operating system version, the configuration of the app when utilizing my service, the time and date of your use of the service, and other statistics.

        %h3 Cookies

        %p Cookies are files containing a small amount of data that is commonly used an anonymous unique identifier. These are sent to your browser from the website that you visit and are stored on your device internal memory.
        %p This service does use these cookies to collect information and to improve its functionality. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this service.

        %h3 Service Providers

        %p I may employ third-party companies and individuals due to the following reasons:

        %ul
            %li To facilitate our service;
            %li To provide the service on our behalf;
            %li To perform service-related services; or
            %li To assist us in analyzing how our service is used.

        %p I want to inform users of this service that these third parties have access to your personal information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.

        %h3 Security

        %p I value your trust in providing us your personal information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and I cannot guarantee its absolute security.

        %h3 Links to Other Sites

        %p This service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by me. Therefore, I strongly advise you to review the privacy policy of these websites. I have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.

        %h3 Children's Privacy

        %p This service do not address anyone under the age of 13. I do not knowingly collect personally identifiable information from children under 13. In the case I discover that a child under 13 has provided me with personal information, I will immediately delete it from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact me so that I am able to execute the necessary actions.

        %h3 Changes to this Privacy Policy

        %p I may update our privacy policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new privacy policy on this page. These changes are effective immediately after they are posted on this page.

        %h3 Contact Us

        %p
            If you have any questions or suggestions about the privacy policy, do not hesitate to
            = link_to 'contact', contact_url, class: 'hyperlink--inherit'
            me.